---
- name: Get CPU, Memory, HDD Usage from Windows
  hosts: windows
  gather_facts: true

  tasks:
    - name: Get CPU Usage (%)
      ansible.windows.win_shell: |
        $cpu = Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 2
        [math]::Round($cpu.CounterSamples[1].CookedValue, 2)
      register: cpu
      changed_when: false

    - name: Get Memory Usage (GB)
      ansible.windows.win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        "mem_total=$([math]::Round(($os.TotalVisibleMemorySize * 1024) / 1GB, 2))"
        "mem_free=$([math]::Round(($os.FreePhysicalMemory * 1024) / 1GB, 2))"
      register: mem
      changed_when: false

    - name: Get HDD Usage (C:)
      ansible.windows.win_shell: |
        $d = Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='C:'"
        "disk_total=$([math]::Round($d.Size / 1GB, 2))"
        "disk_free=$([math]::Round($d.FreeSpace / 1GB, 2))"
      register: disk
      changed_when: false

    - name: Show Stats
      debug:
        msg: >
          CPU: {{ cpu.stdout | float }}% |
          MEM: {{ mem.stdout_lines[0].split('=')[1] }}G total, {{ mem.stdout_lines[1].split('=')[1] }}G free |
          DISK: {{ disk.stdout_lines[0].split('=')[1] }}G total, {{ disk.stdout_lines[1].split('=')[1] }}G free
