---
- name: Get CPU, Memory, HDD Usage from Windows
  hosts: windows
  gather_facts: true

  tasks:
    - name: Get CPU Usage (%)
      ansible.windows.win_shell: |
        $cpu = Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 2
        [math]::Round($cpu.CounterSamples[1].CookedValue, 2)
      register: cpu
      changed_when: false

    - name: Get Memory Usage (GB)
      ansible.windows.win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        "mem_total=$([math]::Round(($os.TotalVisibleMemorySize * 1024) / 1GB, 2))"
        "mem_free=$([math]::Round(($os.FreePhysicalMemory * 1024) / 1GB, 2))"
      register: mem
      changed_when: false

    - name: Get HDD Usage (C:)
      ansible.windows.win_shell: |
        $d = Get-CimInstance Win32_LogicalDisk -Filter "DeviceID='C:'"
        "disk_total=$([math]::Round($d.Size / 1GB, 2))"
        "disk_free=$([math]::Round($d.FreeSpace / 1GB, 2))"
      register: disk
      changed_when: false

    - name: Set Parsed Facts
      set_fact:
        cpu_usage: "{{ cpu.stdout | float }}"
        mem_total: "{{ mem.stdout_lines[0].split('=')[1] | float }}"
        mem_free:  "{{ mem.stdout_lines[1].split('=')[1] | float }}"
        disk_total: "{{ disk.stdout_lines[0].split('=')[1] | float }}"
        disk_free:  "{{ disk.stdout_lines[1].split('=')[1] | float }}"

    - name: Show Stats
      debug:
        msg: |
          === System Usage Stats ===
          CPU Usage       : {{ cpu_usage }} %
          Memory Total    : {{ mem_total }} GB
          Memory Free     : {{ mem_free }} GB
          Disk Total (C:) : {{ disk_total }} GB
          Disk Free (C:)  : {{ disk_free }} GB
