---
- name: Get System Stats from Windows hosts
  hosts: windows
  gather_facts: false

  tasks:
    - name: Retrieve CPU Usage Percent (CookedValue)
      ansible.windows.win_shell: |
        $cpu = Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 2
        $cpuValue = $cpu.CounterSamples[1].CookedValue
        [math]::Round($cpuValue, 2)
      register: cpu_usage_raw
      changed_when: false

    - name: Parse CPU Usage
      ansible.builtin.set_fact:
        cpu_usage_percent: "{{ cpu_usage_raw.stdout | trim | float | default(0) }}"
    - name: DATE AND TIME
        dtg: "Current time (UTC): {{ ansible_date_time.iso8601 }}"

    - name: Retrieve Memory Usage
      ansible.windows.win_shell: |
        $os = Get-CimInstance Win32_OperatingSystem
        $totalMemGB = [math]::Round(($os.TotalVisibleMemorySize * 1024) / 1GB, 2)
        $freeMemGB = [math]::Round(($os.FreePhysicalMemory * 1024) / 1GB, 2)
        $usedMemGB = [math]::Round($totalMemGB - $freeMemGB, 2)
        Write-Output "total_memory=$totalMemGB"
        Write-Output "used_memory=$usedMemGB"
        Write-Output "free_memory=$freeMemGB"
      register: memory_stats_raw
      changed_when: false

    - name: Parse Memory Stats
      ansible.builtin.set_fact:
        total_memory_gb: "{{ memory_stats_raw.stdout_lines[0].split('=')[1] | trim | float }}"
        used_memory_gb: "{{ memory_stats_raw.stdout_lines[1].split('=')[1] | trim | float }}"
        free_memory_gb: "{{ memory_stats_raw.stdout_lines[2].split('=')[1] | trim | float }}"

    - name: Display Stats
      ansible.builtin.debug:
        msg: "{{ dtg }}" "CPU Usage: {{ cpu_usage_percent }}%, Total Memory: {{ total_memory_gb }} GB, Used Memory: {{ used_memory_gb }} GB, Free Memory: {{ free_memory_gb }} GB"
